name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
    - title: '🚀 Features'
      labels:
          - 'feature'
          - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
          - 'fix'
          - 'bugfix'
          - 'bug'
    - title: '🧰 Maintenance'
      labels:
          - 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
    major:
        labels:
            - 'breaking'
    minor:
        labels:
            - 'feature'
    patch:
        labels:
            - 'fix'
            - 'maintenance'
    default: patch
autolabeler:
    - label: 'feature'
      branch:
          - '/feature\/.+/'
    - label: 'hotfix'
      branch:
          - '/hotfix\/.+/'
    - label: 'release'
      branch:
          - '/release\/.+/'
    - label: 'enhancement'
      title:
          - '/enhance/i'
    - label: 'bug'
      title:
          - '/fix/i'
      branch:
          - '/bugfix\/.+/'
    - label: 'documentation'
      files:
          - 'docs/*'
          - '*.md'
template: |
    # 🌟 Release $RESOLVED_VERSION
    
    ## Overview
      🚀 Welcome to version $RESOLVED_VERSION! This release brings a suite of exciting updates and improvements. Dive into the details below to discover what’s new.
    
    ## 🛠 Changes in This Release
    Here's a comprehensive list of what's new and improved in $RESOLVED_VERSION:
    
      $CHANGES
    
    ### 🌟 Highlights
    - **🔥 Key Feature/Improvement**: Briefly describe a standout feature or improvement in this release.
    - **🐛 Significant Bug Fix**: Highlight a critical bug fix, if applicable.
    
    ## 👥 Contributors
    A heartfelt thank you to all the amazing contributors to this release:
    
      $CONTRIBUTORS
    
      Special acknowledgment to [Contributor Name] for significant contributions.
    
      ## 🔍 Comparing with Previous Version
      For a review of changes since the last version ($PREVIOUS_TAG), please refer to our previous release notes.
    
    ## 📚 Repository Information
    - Repository: $REPOSITORY
    - Owner: $OWNER
    
    ## 🔮 Looking Forward
    As we continue to evolve [Product/Service Name], stay tuned for more thrilling updates in our upcoming releases:
    
      - Upcoming features or improvements.
      - Anticipated enhancements in the next versions.
    
      ### 📈 Future Version Expectations
      - Next Patch Version: $NEXT_PATCH_VERSION
      - Next Minor Version: $NEXT_MINOR_VERSION
      - Next Major Version: $NEXT_MAJOR_VERSION
    
    ---
    
    💬 Your feedback and contributions are always welcome. Please feel free to reach out to us with suggestions or comments.
    
    ---
    
    *Automatically generated using Release Drafter*
